export { default as Landing } from './Landing'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Dashboard } from './Dashboard'
export { default as Profile } from './Profile'
export { default as Settings } from './Settings'
